Repository sopel-irc/sopel-github, pull requests merged in 2019-05, with the labels that each got.

#24 webhook: ignore review comments when not "created"
  sopel_modules/github/formatting.py
Labels: enhancement

#27 webhook: Handle re-opening issues/PRs
  sopel_modules/github/formatting.py
Labels: bugfix, enhancement

#30 formatting: Use `splitlines()`
  sopel_modules/github/formatting.py
  sopel_modules/github/github.py
Labels: bugfix

#37 commit: properly pluralize (or don't) "files"
  sopel_modules/github/github.py
Labels: bugfix

#33 Replace `SopelMemory.contains()` with `in` operator
  sopel_modules/github/github.py
  sopel_modules/github/webhook.py
Labels: tweak

#21 webhook: handle release events
  sopel_modules/github/formatting.py
Labels: enhancement

#39 github: fixing error on empty description or commit message
  sopel_modules/github/github.py
Labels: bugfix
