Repository sopel-irc/sopel-github, pull requests merged in 2020-10, with the labels that each got.

#69 formatting: more details in PR output
  sopel_modules/github/formatting.py
Labels: enhancement

#72 webhook: fix error on reconnect
  sopel_modules/github/webhook.py
Labels: bugfix

#75 webhook: Handle issue transfers
  sopel_modules/github/formatting.py
Labels: enhancement, hacktoberfest-accepted

#77 formatting: handle 'converted_to_draft' PR event
  sopel_modules/github/formatting.py
Labels: enhancement, hacktoberfest-accepted

#76 github: add rudimentary handler for file links
  sopel_modules/github/github.py
Labels: enhancement, hacktoberfest-accepted
